Config/configPage.html

Two were misnamed and were failing, but they are not required at all.
Also forgot a single capitalization rename from #1, `BaseDN` -> `BaseDn`.

Remove form/page references from setters

---

LDAP-Auth/LDAP-Auth.csproj
LDAP-Auth/LDAPAuthenticationProviderPlugin.cs
build.yaml

Implements the ChangeEasyPassword method to ensure compatibility with Jellyfin 10.3.4+. Like the ChangePassword method this just throws a NotImplementedException.
Fixes jellyfin/jellyfin#1445 part 1

Fix easypassword failure

---

LDAP-Auth/LDAPAuthenticationProviderPlugin.cs

These are also needed by the plugin to build against 10.3.5. They return empty strings since getting this info is irrelevant for functional purposes. Seems to work fine with my instance on 10.3.5.

Implement the GetPasswordHash functions

---

LDAP-Auth/Config/PluginConfiguration.cs
LDAP-Auth/Config/configPage.html
LDAP-Auth/LDAPAuthenticationProviderPlugin.cs

This pull request adds 2 new options to enable the use of STARTTLS and allow to skip the verification of SSL/TLS certificates when connecting.
Fixes #12

Implementing STARTLS and optional skipping of verification of certificates

---

.gitignore
LDAP-Auth/Config/PluginConfiguration.cs
LDAP-Auth/Config/configPage.html
LDAP-Auth/LDAP-Auth.csproj
LDAP-Auth/LDAPAuthenticationProviderPlugin.cs
build.yaml

Until EasyPin is moved out of the Auth provider I allowed the LDAP plugin to use EasyPin. 
Tested with openldap and latest (master) Jellyfin 
No Jellyfin server changes are required.

Enable EasyPin login

---

LDAP-Auth/Config/configPage.html
LDAP-Auth/LDAP-Auth.csproj
LDAP-Auth/LDAPAuthenticationProviderPlugin.cs
build.yaml

Fix 10.6 errors

---

.github/workflows/build-dotnet.yml
.github/workflows/codeql-analysis.yml

**Description**
CodeQL and the basic dotnet build workflow failed for no apparent reason now that 10.7-rc1 is out, so I went and investigated.
* CodeQL just failed to to me messing up and forgetting to configure .Net 5 :sweat_smile: 
* the basic dotnet build workflow failed to to `--no-restore` at build in the `Release` configuration (actually not sure how that can be since this was 100% the configuration suggested by GitHub themselves) :confused: 
Sorry for messing these up in the previous PR :frowning_face: 
**Changes**
* add setup for .Net 5 in CodeQL workflow
* remove `--no-restore` option from `Release` configured build step in test-build workflow
* change workflow trigger to only run on code relevant changes
**Issues**
* None (just me fixing my own errors)

fix(ci): test-build and codeQL workflow fix

---

LDAP-Auth/Config/PluginConfiguration.cs
LDAP-Auth/Config/configPage.html
LDAP-Auth/LDAP-Auth.csproj
LDAP-Auth/LDAPAuthenticationProviderPlugin.cs
build.yaml

Fixes https://github.com/jellyfin/jellyfin-plugin-ldapauth/issues/34
Thought this was already in, sorry!

Fix case-sensitive username check

---

.github/dependabot.yml
.github/release-drafter.yml
.github/workflows/build-dotnet.yml
.github/workflows/codeql-analysis.yml

As promised in  jellyfin/jellyfin-meta-plugins#3 here a demo of how to use a centralised Release Drafter configuration.
* allow GH workflows to run on changes in .github/**
* simplify the dependabot config for github-actions
* change the Release drafter config to 'extend' the centralised version
* n/a
**NOTE** I am not sure if we want to keep the `commit-message` dependabot config for nuget packages as is, since it will always end up as `fix`-prefix how it stands right now

chore(ci): centralised release-drafter

---

LDAP-Auth/LDAPAuthenticationProviderPlugin.cs

fixes https://github.com/jellyfin/jellyfin-plugin-ldapauth/issues/57
I had the same problem as described in the issue and investigated it a little bit. I could clearly see in my OpenLDAP logs, that the Admin Query returned results, but the debug log message always showed `is admin? False` 
After looking around in the LDAP Library documentation, I could not find a single reference that would confirm the current usage to be valid. Therefore I changed the condition based on the documented methods and now it's working. 
If I'd have to take a guess, I'd say that this might've worked in earlier versions but doesn't anymore, and since this whole block is only triggered on user creation it was probably overlooked when upgrading the dependency.

fix admin lookup condition

---

LDAP-Auth/LDAPAuthenticationProviderPlugin.cs
LDAP-Auth/LdapAuthHandler.cs

Fixes #9.
Tested with Active Directory (functional level 2016) on Windows Server 2019.
Nested groups don't work. The user must be assigned directly to the group specified in the "LDAP User Filter".

Enable automatic referral following

---

LDAP-Auth/Config/configPage.html

In a normal webpage, an alternative to using a global window object field would be to use a named function since re-registering the same named function doesn't register the handler more than once. However, since the HTML is being reloaded, it isn't the same function instance.
Signed-off-by: James Ketrenos <james_github@ketrenos.com>

Fix #92 - Re-registering of "pageshow" handler

---

LDAP-Auth/Config/PluginConfiguration.cs
LDAP-Auth/Config/configPage.html
LDAP-Auth/LDAPAuthenticationProviderPlugin.cs

I needed to be able to limit new users to only have access to specific content on my network. I like the way editing of individual library access is performed, so extended that concept into the LDAP plugin configuration.
THe HTML view is derived from jellyfin-web/src/controllers/dashboard/users/userlibraryaccess.html
Signed-off-by: James Ketrenos <james_github@ketrenos.com>

Add 'Enable All Folders' or selected folder list for LDAP user create

---

LDAP-Auth/Config/configPage.html
LDAP-Auth/LDAPAuthenticationProviderPlugin.cs

This two patch series performs the following:
1. Allow the admin to blank out the LDAP filter for configuring Administrators.
2. Adds additional text to the purpose and use of the LDAP admin filter
3. Adds a check if a user exists and logs in to update their admin state based on if an LDAP filter is configured, and if it has changed vs. their currently configured setting.
Note the question toward the bottom of the second patch -- I wasn't sure if the authentication flow is run for all users, or only those users that have their authenticationProviderId set to the LDAP-Auth. Currently the patch checks to make sure the current provider is set to LDAP prior to updating any access.

Changing the LDAP Admin filter can change existing LDAP authenticating users

---

LDAP-Auth/Api/LdapController.cs
LDAP-Auth/Api/Models/ServerConnectionInfo.cs
LDAP-Auth/Config/PluginConfiguration.cs
LDAP-Auth/Config/configPage.html
LDAP-Auth/LDAPAuthenticationProviderPlugin.cs
LDAP-Auth/LdapAuthHandler.cs

Instead of setting everything up and trying to log in, then checking the log to see what went wrong this adds a button to get immediate feedback on the server portion of the settings panel. Similar can be added to the user/admin filter searches once this is settled.
I also reorganized the settings page into panels so related settings are grouped next to each other (loosely based on the flow of the nextcloud ldap settings pages). Panels can be collapsed, because once you've got your server settings working you might as well be able to hide it while working on the next steps.
**Changes**
- Reorganize and group settings into panels (collapsible but expanded by default)
- Use defaults set on server instead of also filling them in on page load
- Prevents allowable blank fields (such as bind …

Add Settings Tests

---

LDAP-Auth/Api/LdapController.cs
LDAP-Auth/Api/Models/ConnectErrorResponse.cs
LDAP-Auth/Api/Models/LdapFilterResponse.cs
LDAP-Auth/Api/Models/LdapTestErrorResponse.cs
LDAP-Auth/Api/Models/ServerTestResponse.cs
LDAP-Auth/Api/Models/UserFilterInfo.cs
LDAP-Auth/Api/Models/UserSearchAttributes.cs
LDAP-Auth/Api/Models/UserSearchResponse.cs
LDAP-Auth/Config/configPage.html
LDAP-Auth/LDAPAuthenticationProviderPlugin.cs

**Changes**
- Minor cleanup and refactoring to improve reusability of code
- Implemented testing of user/admin filters - displays counts for each and warns if admins aren't users
- Implemented test query of a user log in
**Screenshots**
LDAP User Settings
Valid filters with matches
Empty user filter, admin warning
No user found
User found
Unable to search due to LDAP connection failure
**Issues**
Fixes #40

Add User Settings Tests

---

LDAP-Auth/Api/LdapController.cs
LDAP-Auth/Api/Models/ServerConnectionInfo.cs
LDAP-Auth/Config/PluginConfiguration.cs
LDAP-Auth/Config/configPage.html
LDAP-Auth/LDAPAuthenticationProviderPlugin.cs

Fixes https://github.com/jellyfin/jellyfin-plugin-ldapauth/issues/22
While not perfect, this is as good as the plugin can currently do.

Add ability to use LDAP as password reset provider

---

LDAP-Auth/Config/PluginConfiguration.cs
LDAP-Auth/Config/configPage.html
LDAP-Auth/LDAPAuthenticationProviderPlugin.cs

This adds a support for a memberUid feature (OpenLDAP did not support memberOf in the beginning).
Example admin group with the list of admin uids:
```
dn: cn=syncloud,ou=groups,dc=syncloud,dc=org
objectClass: posixGroup
objectClass: top
gidNumber: 1
cn: syncloud
description: Syncloud
memberUid: user1
memberUid: user2
```
Example user:
```
dn: cn=user1,ou=users,dc=syncloud,dc=org
objectClass: simpleSecurityObject
objectClass: person
objectClass: inetOrgPerson
objectClass: posixAccount
uidNumber: 10
gidNumber: 10
homeDirectory: user1
uid: user1
cn: user1
sn: user1
displayName: user1
description: user1
```
Example config:
```
<LdapAdminBaseDn>cn=syncloud,ou=groups,dc=syncloud</LdapAdminBaseDn>
<LdapAdminFilter>memberUid={username}</LdapAdminFilter>
```
where username is what user enters into …

OpenLDAP admin memberUid support

---

LDAP-Auth/LDAPAuthenticationProviderPlugin.cs

Current release sets _everyone_ as admin... so that's an issue

Fix searching for admin

---

LDAP-Auth/Api/LdapController.cs
LDAP-Auth/Api/Models/ServerConnectionInfo.cs
LDAP-Auth/Config/PluginConfiguration.cs
LDAP-Auth/Config/configPage.html
LDAP-Auth/LDAPAuthenticationProviderPlugin.cs

- Allow user to specify Root CA to validate LDAP server cert against
- Allow user to specify client TLS cert/key for authentication with LDAP server
Proposed implementation for #134

Expand certificate support for LDAP authentication

---

LDAP-Auth/Api/LdapController.cs
LDAP-Auth/Api/Models/UserFilterInfo.cs
LDAP-Auth/Api/Models/UserSearchAttributes.cs
LDAP-Auth/Config/PluginConfiguration.cs
LDAP-Auth/Config/configPage.html
LDAP-Auth/LDAPAuthenticationProviderPlugin.cs

The previous implementation would search for all users that potentially matched the (mandatory) configured search filter, then loop through the results to find a user matching one of the attributes.
This method worked fine for small instances, but became unwieldy for larger LDAP instances, and could even result in a Size Limit Exceeded error for extremely large databases.
This commit introduces a better method by integrating the user search component into the initial LDAP search by way of the search filter. This will ideally result in only a single LDAP search result for a given user rather than potentially dozens or hundreds, reducing both the runtime complexity of the plugin as well as the load on the LDAP server.
This new method has two potential ways of generating the limited search …

Rework search flow to minimize LDAP search results

---

README.md

Changed the build badge to use the new settings in the [issue that the badge previously pointed to](https://github.com/badges/shields/issues/8671), changed the link in the `<a>` tag to point to the test.yaml file.

Fix "build" shields badge

---

LDAP-Auth/Helpers/LdapUtils.cs
LDAP-Auth/LDAPAuthenticationProviderPlugin.cs

This patch sanitizes the `username` input by replacing unsafe characters with their ASCII HEX representation. This is necessary to counteract potential injections of malicious statements into the LDAP search query constructed by the plugin.
Table of unsafe characters and their replacements:
```
\	\\5c
*	\\2a
(	\\28
)	\\29
NUL	\\00
```
References:
https://datatracker.ietf.org/doc/html/rfc4515#section-3
https://cheatsheetseries.owasp.org/cheatsheets/LDAP_Injection_Prevention_Cheat_Sheet.html#search-filter-escaping

Implement proper input sanitization to prevent LDAP injection attacks

---

LDAP-Auth/Api/Models/LdapUser.cs
LDAP-Auth/Config/PluginConfiguration.cs
LDAP-Auth/Config/configPage.html
LDAP-Auth/Helpers/ProfileImageUpdater.cs
LDAP-Auth/LDAPAuthenticationProviderPlugin.cs
LDAP-Auth/LdapProfileImageSyncTask.cs

This PR addresses #85 and implements profile image synchronization from LDAP to Jellyfin.
The profile image is set when a user account is created and automatically synchronized in a configurable interval using a scheduled task. The attribute to retrieve the profile image can be configured and is set to `jpegphoto` by default. Profile image synchronization is disabled by default and can be enabled in the settings.
The profile image is only changed if it has been changed in LDAP. To detect the change a hash of the image is stored in the plugin configuration for the user and compared to the hash of the LDAP attribute when the scheduled task is run. 
This PR has been tested with an LLDAP instance as LDAP-backend, but other LDAP servers should behave the same.

Add profile image synchronization

---

LDAP-Auth/Helpers/PasswordModifyOperation.cs
LDAP-Auth/LDAPAuthenticationProviderPlugin.cs

I implemented the LDAP Password Modify Extended Operation.  Completes #127 and #143.

Implement Password Modify Extended Operation

---

LDAP-Auth/Helpers/LdapUtils.cs
README.md

Some binary images seem to falsely trip the `TryNew`—*maybe* because it contains a string like `567890:hjklmnopqrstuvwxyz` in a couple spots—so it throws an `InvalidOperationException` when it gets to the `uri.Scheme` checks, thus causing both login and the image sync task to fail.
This PR solves the first issue by scanning for any non-printable ASCII control codes (apart from `\r`, `\n` etc.) in the `stringValue` to avoid the false positive entirely.
To solve the second issue for relative paths (or any URI without a scheme), an additional check is added to first ensure the URI is an absolute one. Still an exception, but hopefully much clearer for the user as to what went wrong.

Improve binary/uri ProfileImage handling
